export const API_URL = 'https://app.admss.com/api/v1/';

export const renamedKeys: Record<string, string> = {
    dealType: 'Deal Type',
    dealStatus: 'Deal Status',
    feeDefDocumentation: 'Documentation Fee',
    feeDefvehiclePack: 'Vehicle Pack Fee',
    feeDefTitle: 'Title Fee',
    feeDefTag: 'Tag Fee',
    feeDefTransfer: 'Transfer Fee',
    feeDefSpareTag: 'Spare Tag Fee',
    feeDefSpareTransferTag: 'Spare Transfer Tag Fee',
    taxDefStateVehicleTaxRate: 'State Vehicle Tax Rate',
    stocknumSequental: 'Stock Number is Sequential',
    stocknumPrefix: 'Stock Number Prefix',
    stocknumSuffix: 'Stock Number Suffix',
    stocknumLast6ofVIN: 'Stock Number Last 6 of VIN Symbols',
    stocknumLast8ofVIN: 'Stock Number Last 8 of VIN Symbols',
    stocknumFixedDigits: 'Stock Number Fixed Digits',
    stocknumtiSequental: 'Stock Number Is Sequential',
    stocknumtiPrefix: 'Stock Number Prefix',
    stocknumtiSuffix: 'Stock Number Suffix',
    stocknumtiLast6ofVIN: 'Stock Number Last 6 of VIN Symbols',
    stocknumtiLast8ofVIN: 'Stock Number Last 8 of VIN Symbols',
    stocknumtiFixedDigits: 'Stock Number Fixed Digits',
    stocknumtiFromSoldVehicle: 'Stock Number From Sold Vehicle',
    accountStartNumber: 'Account Start Number',
    accountFixedDigits: 'Account Fixed Digits',
    accountPrefix: 'Account Prefix',
    accountSuffix: 'Account Suffix',
    accountLateFeeMin: 'Account Late Fee Min',
    accountLateFeeMax: 'Account Late Fee Max',
    accountLateFeePercentage: 'Account Late Fee Percentage',
    accountLateFeeGracePeriod: 'Account Late Fee Grace Period',
    contractDefInterestRate: 'Contract Default Interest Rate',
    contractPaymentFrequency: 'Contract Payment Frequency',
    leaseMoneyFactor: 'Lease Money Factor',
    leaseDefaultMileage: 'Lease Default Mileage',
    leaseOverageAmount: 'Lease Overage Amount',
    leaseTerm: 'Lease Term',
    leasePaymentFrequency: 'Lease Payment Frequency',
};
