export const API_URL = 'https://app.admss.com/api/v1/';

export const renamedKeys: Record<string, string> = {
    dealType: 'Deal Type',
    dealStatus: 'Deal Status',
    feeDefDocumentation: 'Documentation Fee',
    feeDefvehiclePack: 'Vehicle Pack Fee',
    feeDefTitle: 'Title Fee',
    feeDefTag: 'Tag Fee',
    feeDefTransfer: 'Transfer Fee',
    feeDefSpareTag: 'Spare Tag Fee',
    feeDefSpareTransferTag: 'Spare Transfer Tag Fee',
    taxDefStateVehicleTaxRate: 'State Vehicle Tax Rate',
    stocknumSequental: 'Stock Number is Sequential',
    stocknumPrefix: 'Stock Number Prefix',
    stocknumSuffix: 'Stock Number Suffix',
    stocknumLast6ofVIN: 'Stock Number Last 6 of VIN Symbols',
    stocknumLast8ofVIN: 'Stock Number Last 8 of VIN Symbols',
    stocknumFixedDigits: 'Stock Number Fixed Digits',
    stocknumtiSequental: 'Stock Number Is Sequential',
    stocknumtiPrefix: 'Stock Number Prefix',
    stocknumtiSuffix: 'Stock Number Suffix',
    stocknumtiLast6ofVIN: 'Stock Number Last 6 of VIN Symbols',
    stocknumtiLast8ofVIN: 'Stock Number Last 8 of VIN Symbols',
    stocknumtiFixedDigits: 'Stock Number Fixed Digits',
    stocknumtiFromSoldVehicle: 'Stock Number From Sold Vehicle',
    accountStartNumber: 'Account Start Number',
    accountFixedDigits: 'Account Fixed Digits',
    accountPrefix: 'Account Prefix',
    accountSuffix: 'Account Suffix',
    accountLateFeeMin: 'Account Late Fee Min',
    accountLateFeeMax: 'Account Late Fee Max',
    accountLateFeePercentage: 'Account Late Fee Percentage',
    accountLateFeeGracePeriod: 'Account Late Fee Grace Period',
    contractDefInterestRate: 'Contract Default Interest Rate',
    contractPaymentFrequency: 'Contract Payment Frequency',
    leaseMoneyFactor: 'Lease Money Factor',
    leaseDefaultMileage: 'Lease Default Mileage',
    leaseOverageAmount: 'Lease Overage Amount',
    leaseTerm: 'Lease Term',
    leasePaymentFrequency: 'Lease Payment Frequency',
    created: 'Created Date',
    index: 'Index',
    itemuid: 'Item UID',
    updated: 'Updated Date',
    useruid: 'User UID',
    locEmail1: 'Location Email 1',
    locEmail2: 'Location Email 2',
    locManager1: 'Location Manager 1',
    locManager2: 'Location Manager 2',
    locName: 'Location Name',
    locPhone1: 'Location Phone 1',
    locPhone2: 'Location Phone 2',
    locState: 'Location State',
    locStreetAddress: 'Location Street Address',
    locWeb: 'Location Website',
    locZIP: 'Location ZIP',
    locuid: 'Location UID',
    uaAddContacts: 'Can Add Contacts',
    uaAddCreditsAndFees: 'Can Add Credits and Fees',
    uaAddDeals: 'Can Add Deals',
    uaAddExpenses: 'Can Add Expenses',
    uaAddInventory: 'Can Add Inventory',
    uaAllowBackDatingPayments: 'Can Allow Backdating Payments',
    uaAllowMobile: 'Can Allow Mobile',
    uaAllowPartialPayments: 'Can Allow Partial Payments',
    uaAllowPaymentCalculator: 'Can Allow Payment Calculator',
    uaAllowPaymentQuote: 'Can Allow Payment Quote',
    uaAllowPrinting: 'Can Allow Printing',
    uaAllowReports: 'Can Allow Reports',
    uaAllowWeb: 'Can Allow Web Access',
    uaChangePayments: 'Can Change Payments',
    uaClientAdmin: 'Can Manage Clients',
    uaCreateUsers: 'Can Create Users',
    uaDeleteAccounts: 'Can Delete Accounts',
    uaDeleteContacts: 'Can Delete Contacts',
    uaDeleteDeal: 'Can Delete Deals',
    uaDeleteInventory: 'Can Delete Inventory',
    uaDeletePayments: 'Can Delete Payments',
    uaEditContacts: 'Can Edit Contacts',
    uaEditDealWashout: 'Can Edit Deal Washout',
    uaEditDeals: 'Can Edit Deals',
    uaEditExpenses: 'Can Edit Expenses',
    uaEditInsuranceOnly: 'Can Edit Insurance Only',
    uaEditInventory: 'Can Edit Inventory',
    uaEditPaidComissions: 'Can Edit Paid Commissions',
    uaEditPayments: 'Can Edit Payments',
    uaEditSettings: 'Can Edit Settings',
    uaLocationAdmin: 'Can Manage Locations',
    uaManager: 'Can Manage',
    uaPrintDealsForms: 'Can Print Deal Forms',
    uaSalesPerson: 'Is Salesperson',
    uaSystemAdmin: 'Is System Administrator',
    uaViewAccounts: 'Can View Accounts',
    uaViewContacts: 'Can View Contacts',
    uaViewCostsAndExpenses: 'Can View Costs and Expenses',
    uaViewDeals: 'Can View Deals',
    uaViewInventory: 'Can View Inventory',
};
